// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wihvailsuulebckjvghl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpaHZhaWxzdXVsZWJja2p2Z2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzQyODEsImV4cCI6MjA2OTQ1MDI4MX0.wyWo96et6Jqca1aRQMCyeXsULwMy2ecZCqyjCbV-r7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});